version: "3"
services:
  development:
    container_name: development
    build: .
    volumes:
      - .:/development
      - ./conan:/root/.conan
    ports:
      - "8089:8089/udp"
      - "8090:8090"